---
- name: build state
  hosts: build
  become: yes

  tasks:
  - name: check git package is present
    apt:  
      name: git
      state: present

  - name: check jdk package is present
    apt: 
      name: default-jdk
      state: present
  
  - name: check maven package is present
    apt:
      name: maven
      state: present

  - name: check git-repo is cloned
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/hw8
      clone: yes

  - name: check artifact is exists
    stat:
      path: /tmp/hw8/target/hello-1.0.war
    register: result

  - name: create artifact, if it does not exist
    shell: mvn package
    args:
      chdir: /tmp/hw8
    when: not result.stat.exists

  - name: copy artifact to master
    fetch: 
      src: /tmp/hw8/target/hello-1.0.war
      dest: /tmp/
      flat: true


- name: prod state
  hosts: prod
  become: yes

  tasks: 
  - name: check jdk package is present
    apt: 
      name: default-jdk
      state: present

  - name: check tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: check tomcat service is started
    service: 
      name: tomcat9
      state: started

  - name: check artifact in webapps directory is exists
    stat: 
      path: /usr/local/tomcat/webapps/hello-1.0.war
    register: result

  - name: copy artifact, if it does not exist
    copy:
      src: /tmp/hello-1.0.war
      dest: /usr/local/tomcat/webapps
    when: not result.stat.exists




